# Generated by Django 3.0.5 on 2020-04-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type_of_product',
            new_name='category',
        ),
    ]
