# Generated by Django 3.0.5 on 2020-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0003_auto_20200413_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
    ]
