# Generated by Django 3.0.5 on 2020-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0004_auto_20200414_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
