# Generated by Django 3.0.5 on 2020-04-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0006_auto_20200414_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=''),
        ),
    ]
