# Generated by Django 3.0.5 on 2020-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petra', '0007_auto_20200414_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(max_length=150, upload_to=''),
        ),
    ]
